title= Autopoiesis: A photographic project
date=2018-10-27
type=post
tags=english, art, sciart, self, identity, photography, visual
status=published
~~~~~~

include::../../headers/constants.adoc[]

NOTE: Some thumbnails of this project are posted in my _Instagram_ account (`xmunch`) with the hashtag `#autopoiesissciartlab`.
You can https://www.instagram.com/xmunch/[subscribe to my feed] or https://www.instagram.com/explore/tags/autopoiesissciartlab/[to the hashtag] itself to be updated. For prints or a photo exhibit you can contact me directly to xmunch@xmunch.com


== What is 'Autopoiesis'?


I am working on a visual project called 'Autopoiesis' for the **SciArt Lab**.

It brings together the quest for personal identity (it is a _self-reflection_) while exploring visual concepts I have previously studied during my former research.

Ideas such as _Complex Adaptive Systems_, _self-organization_ and _emergence_ in biological and social systems are explored through the camera lenses in combination with a deep examination of my own phenomenological experience.


== Some pictures of the project


++++

<style>
.col-sm-12 iframe {
    width: 100% !important;
}

</style>
<div class="row">
<div class="col-sm-12">

<!-- InstaWidget -->
<a href="https://instawidget.net/v/user/xmunch" id="link-9b38b4864a62397ae4d45afddd33c4f6f3f2d1fbbb11c541b4d50426e531fcfe">@xmunch</a>
<script src="https://instawidget.net/js/instawidget.js?u=9b38b4864a62397ae4d45afddd33c4f6f3f2d1fbbb11c541b4d50426e531fcfe&width=600px"></script>

</div></div>
++++


== Theoretical Context

'Autopoiesis' is just a new answer to an old set of questions. Rather than being a fully brand-new experiment, it follows the theoretical steps of my former research from an art-centered approach.

As a multidisciplinary researcher, defining the boundaries of my exploration is not quite easy. I have explored both the nature of the self and the field of complex adaptive systems from mathematical, computational and sociological perspectives. I have also played with anthropology, ethnography and phenomenology trying to find clues about how identity formation takes place in social agents.

'Autopoiesis' is just a new stage of a philosophical inquiry which started long time ago.

=== Personal path

==== Artificial Intelligence, Systems Biology and Philosophy of Mind

Some years ago, after finishing a bachelor in _Computer Systems Engineering_, I moved to Madrid to study a _Master in Artificial Intelligence_. I started to learn about how bots, neurons or ant swarms could develop **emergent properties**. During a a couple of years I was coding basic-AI software, such as agent-based models and cellular automata. Coding software in which something we called _intelligence_ could be observed.

I also discovered the field of **Philosophy of Mind** and how concepts like _cognition_, _consciousness_, _self_, _complexity_ and _self-organization_ could be studied from a scientific and analytical perspective.

Fascinated by this new field, I realized that there was an available position in college to study _artificial consciousness_. Unfortunately, the main researcher never replied my emails. So I finally started to work as a researcher in a **synthetic biology project** within the context of an unconventional computing lab.

Eventually, I found myself working in an research group, exploring communication mechanisms between bacteria. Our goal was to build a _biological computer_ in which bacteria were "reprogrammed genetically" in order to perform human-defined tasks like an electronic computer would do. My work basically consisted in the implementation of a simulator in which we could test how those bacteria would behave and predict the evolution of the system.

After some time working in the lab I would left the _systems biology_ field to work as software engineer for different companies, universities and organizations. However, that experience changed my perception about reality forever. The complexity of communicaton mechanisms and the nature of interdependence in living organisms would stick in my mind for the rest of my life.

Computer Science and Biology were not that different: both explored information processing systems. During the next years, complex networks became the most fascinating of the methapores to understand how the world works.

==== From Bacteria to Humans: the discovery of Complex Adaptive Systems

Developing my career as software engineer and doing some side research was a priority at the time. But I was a young guy, ready to change the world. Worried about inequality and social justice, I pursued another degree in _Cooperation for Development_, something not related at all with my former academic education.

Some time after traveling to Bolivia as a volunteer and visiting some NGOs' projects in Senegal, I started to see how social systems could be conceptualized under the same umbrella than biological and computational systems: **complex adaptive systems**.

In my mind everything started to make sense. As information-processing beings, cells, individuals and societies could be understood as the foundation of several layers of interdependent elements, of emergent properties, of complexity.

The building blocks of life, individuals and societies were just **self-organized units with an autopoietic character**, a combination of functional diversity and decentralized communication infrastructures. **Physical units exchanging flows of ions, chemicals, bits, words or photons**.

Some years later, I got a **PhD in Information Science** after doing some computational modeling of complex adaptive systems and writing several articles, book chapters and a dissertation about _peer-to-peer_ systems.

Some of the theoretical and formal justifications which are the basis of 'Autopoiesis' can therefore be found in my doctoral dissertation, full of _artificial life_ theory, P2P networks, bacteria-based algorithms and sociological models. My dissertation was a formal and theoretical defense of P2P dynamics and was controversial at the time, some years before *blockchain technologies*, protocols like _Dat_ or _IPFS_ and the new ideas about the *distributed web* started to become more mainstream.

==== Finding a multidisciplinary path at the University of Toronto

I had the chance of staying as Visiting Researcher at the _Critical Making Lab_ of the _University of Toronto_ (_UofT_) during the fall of 2014. I arrived without a clear project in mind, looking for an immersive experience in order to open my research to new perspectives while finishing my PhD.

At the time, I was studying how _peer-to-peer_ (P2P) dynamics could be a source of collective production of knowledge. So I thought that a short period as a participant in such a specific environment, full of Canadian critical thinkers and makers, would help me to understand the _Critical Making_ approach and its possible implications for a _P2P society_.

Coming from the field of Computer Science, an specifically from Artificial Intelligence, my research practices and methodological frameworks were mostly quantitative. A large part of my time before going to Toronto I was focused on designing models and algorithms, coding them and analyzing resulting data. In that sense, my study of social phenomena was partially reduced to the analysis of mathematical models and their computational implementations, that is, the simulation of artificial minds and artificial societies.

The focus of my dissertation was far away from actual societies, as a result of considerable simplifications to fit in the criterion of __scientific falsifiability__. Popper's legacy sometimes implies a reductionist perspective; and when the object of study is the social dimension of the human being, the researcher has to dramatically reduce the number of variables.

I was already a guy who rejected the compartmentalization of knowledge and embraced a multidisciplinary project of life. In fact, while working as consultant and developer I studied a wide variety of topics, from Learning Theories to Philosophy of Mind, Cognitive Science or Evolutionary Biology. I had meetings with cognitive psychologists, economists, biologists and physicists. And I learned a lot but, as said, my approach was always quantitative.

However, the experience at _Semaphore Research Cluster_ of the _University of Toronto_ implied a completely different mindset, a chance to “experience” without methodological constraints. The result was kind of an anarchical _grounded theory_ approach that allowed me to observe and participate as a member of the team.

_UofT_ was a game-changer. I had meetings with philosophers, artists, historians, sociologists, designers,… even a cartoonist and a film maker. Those human-based P2P dynamics really opened my mind to the actual meaning of the word “knowledge" (so much more than my computational simulations).

I learned the basis of 3D printing and physical computing. I learned about _situated learning. I could see how artists and academics with a background in humanities explored new materials, electronic devices and micro-controllers with extraordinary skills. I tested sensors and actuators and got a sense of what it is possible to make, discussing with everyone about potential projects, critical issues and cultural engagements.

In a sense, the Critical Making Lab destroyed part of my mental constraints. It provided new intellectual and hands-on tools, new human experiences and an open and critical mindset. It also gave me a clue about what information means and about the implications of technology in critical reflection and social transformation.

My research and my projects never again could fit in one specific field. No technology without humanities. No science without arts.

==== Postdoctoral research

===== Discovering visual ethnography

After my PhD, I moved to the United States and started to develop the http://sciartlab.com[SciArt Lab] while in residence at the _LIS Department_ of the _University of North Carolina at Greensboro_.

Without the constraints of a doctoral program, I decided to go deeper in some of my old questions. It was time to move forward, beyond software, neurons and genes. Explore another layer of complex adaptive systems and social interactions. Jump to the real world.

On the top of genetics and cognition, human beings have an extra layer of information processing: culture. And the US was full of social agents with very different social contexts and cultural backgrounds. It was a multicultural society.

Multiculturalism was a fascinating topic, as appealing as biodiversity, as appealing as the distributed and heterogeneous P2P networks of my PhD. A new field of research. The project http://xmunch.com/blog/['Rhizome Ethnographies'] was born:

> After several years exploring, from a computational perspective, the evolution of social complexity in heterogeneous and decentralized agent-based models, I have decided to start a new stage of research. With this side project, I would like to study the evolution of identity/identities in real social agents. Specifically exploring heterogeneous societies through the observation of their ethnic, linguistic and cultural contexts, and using visual ethnography to learn about transnational identities and multiculturalism.

> So let’s say that I am moving from the fields of Computer Science and Information Science to a new multidisciplinary approach closer to the domains of Sociology and Cultural Anthropology. From software simulations of artificial agents to multicultural communities of actual people.

'Rhizome Ethnographies' was a two years experiment which ended with a documentary about the US and a multimedia website. But it was also an starting point to a new life of self-conducted research under the framework of the SciArt Lab.

> Considering this new stage as a chosen path for knowledge crawling, I would consider it both research, game and art. Besides that, naturally, I would also consider this project a way of self-exploration. [...] I realized that I want to know more about the human being as a social construct. And I want to know it from my own subjective point of view, the point of view of another social construct.


The first part of my documentary 'Looking for Identity' was released in 2017. It can be http://www.sciartlab.com/movie[watched for free here].

The theoretical and visual outcomes of the Rhizome Ethnographies project:  http://xmunch.com/blog/[can also be found here].

===== Discovering phenomenological research

During the first years of the SciArt Lab, I developed other projects in which there were not clear boundaries between art, science and technology. I published proofs-of-concept, software experiments and aesthetic projects without worrying too much about theoretical frameworks or academic constraints.

I implemented cellular automata with emergent properties for digital music composition, generative visual art tools, open-source virtual reality components,... Slowly, first-person experience became more important than objectivity. Music and visual arts became a tool for my own self-exploration.

After couple of years living in the US, the quest for social agents' identity in a multicultural society, and my own immersion in a different environment, implied a lot of cognitive experiences, cultural challenges  and the gradual deconstruction of my own 'persona'. 

Coming back to Spain and having to face a reverse culture shock made it even more clear. 'Who I am?' became the most complex and fascinating question.

The word "identity" started to replace the word "society" in my research priorities. Understand my own first-person experience looked more challenging and difficult than explore others' behavior or identity formation. Even the environment looked more interesting if understood from a pure phenomenological perspective. 

=== Conclusion

This explanation can be useful to understand the theoretical foundations of the project (and most of my current work for the SciArt Lab). 

Currently, I work as **Blockchain Expert** for *Enxendra Technologies*, where I will continue my _R&D in P2P Systems_. A the same time I am focused in the experiments of the SciArt Lab. And additionally, as a side project, in the quest for personal identity through photography :)

So complex. So simple. Autopoiesis.